### ISSUE TITLE
Case Plan: Initial type of Case Plan can only be entered once. Subsequent Case Plans i.e. 2nd onwards can only be follow ups.

### ISSUE THREAD

**Issue by tobiasmakai** [BlueCodeSystems/opensrp-client-ecap-chw#455]
Some constraints;
Type of Case Plan: Required
Domain: Required
Date created: Required
Vulnerability identified from Assessment: Required
Goal: Required
Services to be provided by CW: Not Required  (because service can either be provided by CW or referred)
Services to be Referred: Not Required (because service can either be provided by CW or referred)
Institution where service to be referred: Required (field should only show when the field services to be referred is filled in)
Due Date: Required
Quarter: Required
Status: Required
Comment: Not Required

**Comment by chobela** [comment]
@tobiasmakai It will be very difficult to determine whether a plan is a follow up. For example, if a plan is Schooled, and already has an initial plan, when we are now inserting "Healthy", the case worker will have to select Initial again, because its Initial for "Healthy" this time.

It could have been easier if we were saving a case plan as a whole. but we are saving by domains. So kindly provide more help on this.

**Comment by tobiasmakai** [comment]
Let us find a way of saving a case plan as a whole then. As per the primary tools, they have been doing is as a whole. Whereby the user first indicates whether it is an initial or updated (in our case follow-up) case plan.
![image](https://user-images.githubusercontent.com/25362528/148682551-bdd00a61-8b4c-4df6-a62a-cfd27e43ce78.png)

**Comment by chobela** [comment]
@tobiasmakai I see..
